package cn.springmvc.dao;

import cn.springmvn.model.LoginInfo;
import cn.springmvn.model.LoginInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int countByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int deleteByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int insert(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int insertSelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    List<LoginInfo> selectByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    LoginInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") LoginInfo record, @Param("example") LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int updateByExample(@Param("record") LoginInfo record, @Param("example") LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int updateByPrimaryKeySelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbggenerated Sun Jun 11 13:21:12 CST 2017
     */
    int updateByPrimaryKey(LoginInfo record);
}